version: '3'
services:
  db:
    container_name: carta-db
    image: "postgres:9.6.5"
    environment:
      POSTGRES_PASSWORD: dev1
      POSTGRES_USER: carta
      POSTGRES_DB: eshares_dev
    expose:
      - "3306"
  redis:
    container_name: carta-redis
    image: "redis:3.2.11"
    command:
      - redis-server
    expose:
      - "6379"
  web:
    depends_on:
      - db
      - redis
    container_name: carta-web
    image: "esharesinc/ubuntu-dev"
    volumes:
      - "/work:/work"
      - "/work:/work"
    links:
      - db
      - redis
    command:
      - python
      - manage.py
      - runserver
      - "0.0.0.0:8000"
    ports:
      - "8000:8000"

networks:
  default:
    external:
      name: topenguins
